version: "3.8"

# the services part
services:
  #mariadb
  mariadb:
    image: mariadb:user
    container_name: mariadb
    build: ./srcs/requirements/mariadb
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql
    env_file :
      - ./srcs/.env
    networks :
      - inception
    restart: always

  #nginx
  nginx:
    image: nginx:user
    container_name: nginx
    build: ./srcs/requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
    env_file :
      - ./srcs/.env
    networks:
      - inception
    restart: always

  #wordpress
  wordpress:
    image: wordpress:user
    container_name: wordpress
    build: ./srcs/requirements/wordpress
    ports:
      - "9000:9000"
    #   - "8080:80"
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    env_file :
      - ./srcs/.env
    networks:
      - inception
    restart: always

  #bonus
  #site
  website:
    image: website
    build:
      context: ./srcs/bonus/website
    ports:
      - "1029:1029"
    container_name: website
    networks:
      - inception
    restart:
      always


# the volumes part
volumes:
  mariadb:
    name: mariadb
    driver_opts:
      device: /home/rseelaen/data/mariadb
      o : bind
      type : none
  wordpress:
    name: wordpress
    driver_opts:
      device: /home/rseelaen/data/wordpress
      o : bind
      type : none

# the networks part
networks:
  inception:
    name: inception